### ISSUE TITLE
Still alive? GeoSPARQL?

### ISSUE THREAD

**Issue by nicholascar** [quoll/mulgara#11]
Hi @quoll, is this still a live project? I see that the "last updated" README comment is from 2016 but that you've recently pushed some small updated.

I am interested as a member of the OGC's [GeoSPARQL Standards Working Group](https://github.com/opengeospatial/ogc-geosparql) to know whether this, and all, triplestores implement or plan on implementing GeoSPARQL.

Thanks, Nick

**Comment by quoll** [comment]
Hi Nick,

Not really, no. I’ve done some tweaks when people have asked, but I’m not
actively doing anything with it anymore. I’m working on a new graph
database instead (Asami). It’s based on a similar design, but it’s written
in Clojure, and targets web browsers as well as the JVM. The new language
also makes it faster and easier to bring in new features. So, Mulgara just
doesn’t appeal as much now.

Regards,
Paula Gearon

**Comment by nicholascar** [comment]
OK, thanks, I see you mean [Asami](https://github.com/threatgrid/asami). I'm both interested in that for the same reason as Mulgara (GeoSPARQL) but also I have other interests. Could you drop me an email so I can ask you privately? My email address is in my GitHub profile. Thanks.
